<html>
<head>
<?php include '_scripts.html'; ?>
<script src="_extends.js"></script>
<script src="_authenticate.js"></script>
<script src="_reports.js"></script>
<script src="_stub.php"></script>

<link href="style.css" rel="stylesheet" type="text/css" />
<script>
$(document).ready(function(){
    var artFormSelect = $("#artFormSelect");
    
    var artForms = $.AEDartforms;
    var programTypes = $.AEDprogramtypes;
    
    for (var i = 0; i < artForms.length; i++) {
        $("#artFormSelect").append("<option>"+artForms[i]+"</option>");
        $("#programTypeSelect").append("<option>"+programTypes[i]+"</option>");
    }
    
})

function objectSerialize(form) {
    var o = {};
    var a = form.serializeArray();
    $.each(a, function() {
        if (o[this.name] !== undefined) {
            if (!o[this.name].push) {
                o[this.name] = [o[this.name]];
            }
            o[this.name].push(this.value || '');
        } else {
            o[this.name] = this.value || '';
        }
    });
    return o;
};


function generateJSONByArtForm(inputs) {
    console.log("Just generated by art form");
    console.log(inputs);
    var url = "https://www.googleapis.com/fusiontables/v1/query?sql="
    
    var sql = "SELECT 'Donor First Name' ";
        sql += "FROM ";
        sql += ("'" + $.AEDtables["Donations"] + "'");
        
        sql += " WHERE "
        sql += " 'Date on Check' > "
        console.log(sql);
}

function generateJSONByProgramType(inputs) {
    console.log("Just generated by program type");
    console.log("Serialized: " + inputs.serialize());
}

function generateJSONBySchoolName(inputs) {
    console.log("Just generated by school name");
    console.log("Serialized: " + inputs.serialize());
}

$(function(){
     $('.logout').click(function(e){
            $.LogOut()
     })
    $.Auth(function(){ 
         var token = $.Hash.access_token
         $( '.token' ).text( token )
         //debugger;
         //$.Reports.Header = ""
         $.Reports.List()
    })
})
</script>
</head>
<body>
<?php include '_header.html'; ?>

    <div class="container">

    <h1>Reports</h1>
    <p>
       Generate reports.
    </p>

    
      <br/>
      <a href="#" class="logout">Lout Out of Google</a>
    <pre class="token">
    </pre>
    
        <div id=byArtForm>
            <form id=generateReportByArtForm>
            <table id=artFormTable>
                <tr><th>   <label>By Art Form</label> </th><td>  <select name=artForm id=artFormSelect ></select> </td></tr>
                <tr><td><label>Start Date</label> <input name=start placeholder="MM/DD/YY" /></td>  <td><label>End Date</label> <input name=end placeholder="MM/DD/YY" /></td></tr>
            </table>
            
            <button type=button onClick="generateJSONByArtForm($('#artFormTable :input'))">Go!</button>
            </form>
            
            
            <hr>
        </div>
        
        <div id=byProgramType>
            <form>
            <table id=programTypeTable>
                <tr><th>   <label>By Program Type</label> </th><td>  <select id=programTypeSelect ></select> </td></tr>
                <tr><td><label>Start Date</label> <input placeholder="MM/DD/YY" /></td>  <td><label>End Date</label> <input placeholder="MM/DD/YY" /></td></tr>
            </table>
            
            <button type=button onClick="generateJSONByProgramType($('#programTypeTable :input'))">Go!</button>
            </form>
            
            <hr>
        </div>
        
        <div id=bySchool>
            <form id=generateReportBySchool>
            <table>
                <tr><th>    <label>By School</label> </th><td> <select id=schoolSelect></select> </td></tr>
                <tr><td><label>Start Date</label> <input placeholder="MM/DD/YY" /></td>  <td><label>End Date</label> <input placeholder="MM/DD/YY" /></td></tr>
            </table>
            
            <button type=button onClick="generateJSONBySchoolName($('#schoolTable :input'))">Go!</button>
            
            <hr>
        </div>
        

    </div>
    
<?php include '_footer.html'; ?>
</body>

</html>